import LocalStorageService from "@/api/LocalStorageService.js";
import GeoService from "@/api/GeoService.js";

var store = LocalStorageService.get("fu-products");
if (typeof store == "undefined") store = {};

var companyNames = [
  "Mother Dairy",
  "MTR Foods",
  "Orissa State Cooperative Milk Producers' Federation",
  "Parle Agro",
  "Parle Products",
  "Patanjali Ayurved",
  "Perigreen",
  "Pulla Reddy Sweets",
  "Punjabi Chandu Halwai Karachiwala",
  "Rajesh Masala",
  "REI Agro Limited",
  "Ruchi Soya",
  "Shanthi Feeds",
  "Skylark Group",
  "Sri Krishna Sweets",
  "Suguna Foods",
  "Suminter India Organics",
  "Tasty Bite",
  "Vadilal",
  "Indonesia",
  "Indofood",
  "Mayora Indah",
  "Italy",
  "Amedei",
  "Amica Chips",
  "Auricchio",
  "Autogrill",
  "Balconi",
  "Balocco",
  "Barilla Group",
  "Bartolo Nardini",
  "Bertagni",
  "Campari Group",
  "Carapelli",
  "Cielo",
  "Cirio",
  "Coppola Foods",
  "De Cecco",
  "Divella",
  "Domori",
  "Elledi",
  "Ferrero SpA",
  "Gelati Cecchi",
  "Giovanni Rana",
  "Girolamo Luxardo",
  "Granarolo",
  "Grom",
  "Guglielmo coffee",
  "Gustobene",
  "La Molisana",
  "Lavazza",
  "Lazzaroni",
  "Loacker",
  "Marzadro Distillery",
  "Massimo Zanetti Beverage Group",
  "Nardini (grappa)",
  "Nonino Grappa",
  "Parmalat",
  "Pernigotti",
  "Polli",
  "Saclà Italia",
  "San Carlo",
  "Sterilgarda",
  "Venchi",
  "Vicenzi",
  "Voiello",
  "Ireland",
  "Abbey Cheese Company",
  "Abrakebabra Investments",
  "Ardsallagh Goat Farm",
  "Barry's Tea",
  "Béal Organic Cheese",
  "Bewley's",
  "Bluebell Falls",
  "Burren Smokehouse",
  "Butlers Chocolates",
  "Cahill's Farm Cheese",
  "Carlow Brewing Company",
  "Carrigaline Farmhouse Cheese",
  "C&C Group",
  "Donegal Creameries",
  "Flahavan's",
  "Fyffes",
  "Gleeson Group",
  "Greencore",
  "Hadji Bey",
  "Irwin's Bakery",
  "Kerry Group",
  "Lakeland Dairies",
  "Lyons Tea (Ireland)",
  "Mauds Ice Creams",
  "Murphys Ice Cream",
  "Nobó",
  "Old Bushmills Distillery",
  "Ornua",
  "R&H Hall",
  "Shamrock Foods",
  "Tayto (Northern Ireland)",
  "Tayto (Republic of Ireland)",
  "Valeo Foods",
  "Israel",
  "Angel Bakeries",
  "Berman's Bakery",
  "Osem",
  "Prigat",
  "Strauss",
  "Tara",
  "Yehuda Matzos",
  "Japan",
  "Ajinomoto",
  "Asahi Breweries",
  "Calbee",
  "Ezaki Glico",
  "Fujimitsu Corporation",
  "Fujiya",
  "House Foods",
  "Kabaya",
  "Kagome",
  "Kikkoman"
];

var productNames = [
  "papayas",
  "pesto",
  "lemons",
  "mesclun greens",
  "tortillas",
  "cider",
  "balsamic vinegar",
  "sausages",
  "eggs",
  "spinach",
  "remoulade",
  "plums",
  "chutney",
  "soybeans",
  "leeks",
  "flax seed",
  "flounder",
  "cumin",
  "focaccia",
  "beets",
  "pink beans",
  "ricotta cheese",
  "tartar sauce",
  "almonds",
  "aioli",
  "tomato sauce",
  "cream cheese",
  "quail",
  "apples",
  "cooking wine",
  "succotash",
  "cannellini beans",
  "basil",
  "strawberries",
  "chile peppers",
  "horseradish",
  "pecans",
  "pinto beans",
  "rice",
  "won ton skins",
  "dates",
  "prunes",
  "artichokes",
  "water",
  "ancho chile peppers",
  "shrimp",
  "asiago cheese",
  "coconut oil",
  "powdered sugar",
  "avocados",
  "cocoa powder",
  "barley",
  "bourbon",
  "bagels",
  "pico de gallo",
  "white chocolate",
  "cod",
  "wine",
  "amaretto",
  "octopus",
  "anchovy paste",
  "applesauce",
  "cherries",
  "wild rice",
  "butter",
  "bean sauce",
  "jack cheese",
  "navy beans",
  "sea cucumbers",
  "rose water",
  "clams",
  "green beans",
  "vegemite",
  "green onions",
  "margarine",
  "Kahlua",
  "potato chips",
  "pine nuts",
  "melons",
  "unsweetened chocolate",
  "cookies",
  "paprika",
  "pancetta",
  "acorn squash",
  "garlic",
  "parsley",
  "pickles",
  "hamburger",
  "baking powder",
  "brunoise",
  "walnuts",
  "sherry",
  "pineapples",
  "wine vinegar",
  "marmalade",
  "turnips",
  "mussels",
  "sage",
  "thyme",
  "cream of tartar",
  "figs",
  "moo shu wrappers",
  "mustard",
  "peaches",
  "venison",
  "condensed milk",
  "red snapper",
  "mayonnaise",
  "molasses",
  "brown sugar",
  "poultry seasoning",
  "bard",
  "pasta",
  "corn flour",
  "monkfish",
  "yogurt",
  "grouper",
  "pumpkin seeds",
  "almond extract",
  "tea",
  "rosemary",
  "hazelnuts",
  "rice paper",
  "bacon grease",
  "radishes",
  "Canadian bacon",
  "cactus",
  "portabella mushrooms",
  "brussels sprouts",
  "soymilk",
  "plum tomatoes",
  "breadcrumbs",
  "swordfish",
  "water chestnuts",
  "cremini mushrooms",
  "maple syrup",
  "sardines",
  "Mandarin oranges",
  "squid",
  "celery seeds",
  "black beans",
  "veal",
  "raisins",
  "sweet peppers",
  "chicken",
  "shitakes",
  "bouillon",
  "spearmint",
  "granola",
  "squash",
  "bean sprouts",
  "mustard seeds",
  "bass",
  "marshmallows",
  "tomatoes",
  "eggplants",
  "herring",
  "dried leeks",
  "tonic water",
  "coconut milk",
  "barbecue sauce",
  "red beans",
  "custard",
  "oatmeal",
  "tuna",
  "rhubarb",
  "snow peas",
  "ice cream",
  "limes",
  "eel",
  "pears",
  "pumpkins",
  "date sugar",
  "pig's feet",
  "steak",
  "french fries",
  "oregano",
  "mackerel",
  "chicory",
  "baguette",
  "lobsters",
  "artificial sweetener",
  "cheddar cheese",
  "sazon",
  "curry paste",
  "olive oil",
  "chipotle peppers",
  "English muffins",
  "brazil nuts",
  "fennel",
  "baking soda",
  "andouille sausage",
  "soy sauce",
  "split peas",
  "mozzarella",
  "truffles",
  "snap peas",
  "buckwheat",
  "cayenne pepper",
  "provolone"
];

export default {
  defaultCode() {
    return {
      country: 0,
      company: 1234,
      product: 5678
    };
  },
  parseCode(code) {
    if (code) {
      var str = "" + code;
      return {
        country: str.substring(0, 1),
        company: str.substring(1).substring(0, str.length / 2 - 1),
        product: str.substring(1).substring(str.length / 2, str.length - 1)
      };
    } else {
      return this.defaultCode();
    }
  },
  getProductDetails(code) {
    if (code) {
      if (typeof store[code] != "undefined") {
        return store[code];
      } else {
        var location = GeoService.getRandomLocation();
        var object = {
          name: productNames[Math.floor(Math.random() * productNames.length)],
          company:
            companyNames[Math.floor(Math.random() * companyNames.length)],
          code: this.parseCode(code),
          location: location.location,
          distance: location.distance
        };
        store[code] = object;
        LocalStorageService.save("fu-products", store);
        return object;
      }
    } else {
      return {
        image: "",
        name: "product name",
        company: "company name",
        code: this.defaultCode(),
        location: {
          lon: 0,
          lat: 0
        }
      };
    }
  }
};
